[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bot-trade"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
include = ["bot_trade*"]
