ppo_small: {algorithm: PPO, total_steps: 2048, n_envs: 2, device: cpu, vecnorm: true}
ppo_large: {algorithm: PPO, total_steps: 200000, n_envs: 8, device: "cuda:0", vecnorm: true}
sac_cpu_smoke: {algorithm: SAC, total_steps: 4096, n_envs: 1, device: cpu, vecnorm: true}
td3_small: {algorithm: TD3, total_steps: 8192, n_envs: 2, device: "cuda:0"}
tqc_small: {algorithm: TQC, total_steps: 8192, n_envs: 2, device: "cuda:0"}
