binance:
  rest: https://testnet.binance.vision
  ws: wss://testnet.binance.vision/ws
  recv_window: 5000
  weight_limit: 1200
  routes:
    /api/v3/order: 1
    /api/v3/account: 5
    /api/v3/ticker/price: 1
  time_sync: false
bybit:
  rest: https://api-testnet.bybit.com
  ws: wss://stream-testnet.bybit.com/realtime
  recv_window: 5000
  weight_limit: 100
  routes:
    /v5/order/create: 1
    /v5/order/cancel: 1
    /v5/account/wallet-balance: 5
    /v5/market/tickers: 1
  time_sync: false
