pipeline:
  - macd: { fast: 12, slow: 26, signal: 9 }
  - rsi: { period: 14 }
  - atr: { period: 14 }
  - realized_vol: { window: 60 }
  - spread_bp: { window: 10 }
  - depth_top: { window: 5 }
post:
  - zscore: { on: "returns", window: 100 }
