symbols: [BTCUSDT]
frames: [1m]
devices: [cpu]
max_parallel_runs: 1
defaults:
  train_rl:
    total_steps: 100
    n_envs: 1
    device: cpu
    headless: true
    resume_auto: false
    allow_synth: false
