name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: ruff check bot_trade/backtest bot_trade/eval bot_trade/runners bot_trade/tools tests/unit --fix
      - run: python -m py_compile $(git ls-files 'bot_trade/**/*.py' 'bot_trade/*.py')
      - run: PYTHONPATH=. pytest -q
      - run: PYTHONPATH=. python -m bot_trade.tools.paths_doctor --symbol BTCUSDT --frame 1m --strict
