name: Smoke

on:
  push:
  pull_request:

jobs:
  linux-cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python -m py_compile $(git ls-files 'bot_trade/config/*.py' 'bot_trade/tools/*.py' 'bot_trade/eval/*.py' 'bot_trade/strat/*.py' 'bot_trade/env/*.py' 'bot_trade/train_rl.py')
      - run: python -m bot_trade.tools.gen_synth_data --symbol BTCUSDT --frame 1m --out data_ready
      - run: python -m bot_trade.train_rl --algorithm PPO --symbol BTCUSDT --frame 1m --device cpu --n-envs 1 --n-steps 32 --batch-size 32 --total-steps 64 --headless --allow-synth --data-dir data_ready
      - run: python -m bot_trade.tools.eval_run --symbol BTCUSDT --frame 1m --run-id latest | grep '\[EVAL\]'
      - run: python -m bot_trade.tools.sweep --symbol BTCUSDT --frame 1m --out-dir sweeps/ci --algo-grid "PPO" --param-grid "n_steps=[32];batch_size=[32]" --trials 1 --allow-synth --headless --data-dir data_ready
      - run: python -m bot_trade.tools.dev_checks
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            reports/**/charts/*.png
            reports/**/performance/*
            sweeps/**
