name: Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run smoke script
        shell: pwsh
        run: scripts/smoke_win.ps1
