name: Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e .
      - run: python -m py_compile $(git ls-files 'bot_trade/**/*.py' 'bot_trade/*.py')
      - run: python -m bot_trade.tools.gen_synth_data --symbol BTCUSDT --frame 1m --out data_ready
      - run: python -m bot_trade.train_rl --algorithm PPO --symbol BTCUSDT --frame 1m --device cpu --n-envs 1 --n-steps 32 --batch-size 32 --total-steps 64 --headless --allow-synth --data-dir data_ready
      - run: python -m bot_trade.tools.eval_run --symbol BTCUSDT --frame 1m --run-id latest
      - run: python -m bot_trade.train_rl --algorithm SAC --continuous-env --symbol BTCUSDT --frame 1m --device cpu --n-envs 1 --n-steps 32 --batch-size 32 --total-steps 64 --headless --allow-synth --data-dir data_ready
      - run: python -m bot_trade.tools.eval_run --symbol BTCUSDT --frame 1m --run-id latest
      - run: python -m bot_trade.tools.sweep --mode random --n-trials 4 --symbol BTCUSDT --frame 1m --algorithm SAC --continuous-env --headless --allow-synth --data-dir data_ready
      - run: python -m bot_trade.tools.train_long_run --algorithm SAC --continuous-env --symbol BTCUSDT --frame 1m --headless --allow-synth --data-dir data_ready --preset training=sac_cont_cpu_smoke --preset net=tiny --save-every 32 --eval-every 32 --max-steps 32
      - run: python -m bot_trade.tools.dev_checks --symbol BTCUSDT --frame 1m --run-id latest
      - run: python -m bot_trade.tools.mk_artifacts_index --symbol BTCUSDT --frame 1m --run-id latest --algorithm SAC || true
      - run: python -m bot_trade.tools.print_version
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/**/charts/*.png
            reports/**/tearsheet.html
            reports/**/sweep_*/summary.csv
            reports/**/sweep_*/summary.md
            reports/**/sweep_*/runs.jsonl
            reports/**/summary.csv
            reports/**/summary.md
            reports/**/runs.jsonl
            reports/**/checkpoints/index.csv
            reports/**/artifacts/index.json
