# Default reward shaping: balanced profit with mild risk penalties
weights:
  base_pnl: 1.0        # primary profit term
  risk_drawdown: -0.5  # penalize drawdowns
  slippage_penalty: -0.2  # punish slippage costs
clamps:
  base_pnl: {min: -5.0, max: 5.0}        # limit extreme profit influence
  risk_drawdown: {min: -5.0, max: 5.0}    # cap drawdown penalty
  slippage_penalty: {min: -5.0, max: 5.0} # cap slippage impact
global_clamp: {min: -10.0, max: 10.0}     # safety clamp on total reward
